version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: bana_software
      POSTGRES_PASSWORD: BANASOFTWARE
      POSTGRES_DB: banasoftware
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

  db_test:
    image: postgres
    environment:
      POSTGRES_USER: bana_software
      POSTGRES_PASSWORD: BANASOFTWARE
      POSTGRES_DB: banasoftware_test
    ports:
      - "5433:5432"
    volumes:
      - db_data_test:/var/lib/postgresql/data
volumes:
  db_data_dev:
  db_data_test:
